
// Authors:
//      * Azucena Rodriguez Flores
//      * Miguel Angel Avila Garcia
// Description:  
// Date: April 30th 2026
 
// Latest Update:
// Date:
// By:


const PERMISSIONS = {

    // PUBLIC: not auth required
    LOGIN:                      0x00000001,
    REGISTER:                   0x00000002,
    VERIFY_EMAIL:               0x00000004,
    VIEW_JOBS:                  0x00000008,
    VIEW_JOB_DETAIL:           0x00000010,

    // AUTH: any logged-in user
    LOGOUT:                     0x00000020,
    VIEW_OWN_PROFILE:           0x00000040,
    EDIT_OWN_PROFILE:           0x00000080,

    //  STUDENT - INTERN - GRADUATE
    UPLOAD_CV:                  0x0000100,
    ROLL_ME:                    0x0000200,
    APPLY_TO_JOB:               0x0000400,
    VIEW_OWN_APPLICATIONS:      0x0000800,

    // COMPANY
    CREATE_JOB_POSTING:         0x00001000,
    EDIT_OWN_JOB_POSTING:       0x00002000,
    DELETE_OWN_JOB_POSTING:      0x00004000,
    VIEW_OWN_APPLICANTS:        0x00008000,
    UPDATE_APPLICATION_STATUS: 0x00010000,

    // ADMIN ONLY 
    APPROVE_COMPANY:            0x00020000,
    REJECT_COMPANY:             0x00040000,
    APPROVE_JOB_POSTING:    0x00080000,
    REJECT_JOB_POSTING:     0x00100000,
    EDIT_ANY_JOB_POSTING:       0x00200000,
    DELETE_ANY_JOB_POSTING:     0x00400000,
    VIEW_ALL_USERS:             0x00800000,
    ACTIVATE_USER:              0x01000000,
    DEACTIVATE_USER:            0x02000000,
    DELETE_USER:                0x04000000,
    CHANGE_USER_ROLE:           0x08000000,
    VIEW_ALL_APPLICATIONS:      0x10000000,
    VIEW_ALL_JOB_POSTINGS:      0x20000000,
    SEND_NOTIFICATION:          0x40000000,
    VIEW_AUDIT_LOG:             0x80000000,
    VIEW_REPORTS:               0x100000000, // TO_DO: pending implementation     

}



const STUDENT_PERMISSIONS = [
  PERMISSIONS.LOGIN,
  PERMISSIONS.REGISTER,
  PERMISSIONS.VERIFY_EMAIL,
  PERMISSIONS.VIEW_JOBS,
  PERMISSIONS.VIEW_JOB_DETAIL,
  PERMISSIONS.LOGOUT,
  PERMISSIONS.VIEW_OWN_PROFILE,
  PERMISSIONS.EDIT_OWN_PROFILE,
  PERMISSIONS.UPLOAD_CV,
  PERMISSIONS.ROLL_ME,
  PERMISSIONS.APPLY_TO_JOB,
  PERMISSIONS.VIEW_OWN_APPLICATIONS,
];
 
const INTERN_PERMISSIONS = [
  PERMISSIONS.LOGIN,
  PERMISSIONS.REGISTER,
  PERMISSIONS.VERIFY_EMAIL,
  PERMISSIONS.VIEW_JOBS,
  PERMISSIONS.VIEW_JOB_DETAIL,
  PERMISSIONS.LOGOUT,
  PERMISSIONS.VIEW_OWN_PROFILE,
  PERMISSIONS.EDIT_OWN_PROFILE,
  PERMISSIONS.UPLOAD_CV,
  PERMISSIONS.ROLL_ME,
  PERMISSIONS.APPLY_TO_JOB,
  PERMISSIONS.VIEW_OWN_APPLICATIONS,
];
 
const GRADUATE_PERMISSIONS = [
  PERMISSIONS.LOGIN,
  PERMISSIONS.REGISTER,
  PERMISSIONS.VERIFY_EMAIL,
  PERMISSIONS.VIEW_JOBS,
  PERMISSIONS.VIEW_JOB_DETAIL,
  PERMISSIONS.LOGOUT,
  PERMISSIONS.VIEW_OWN_PROFILE,
  PERMISSIONS.EDIT_OWN_PROFILE,
  PERMISSIONS.UPLOAD_CV,
  PERMISSIONS.ROLL_ME,
  PERMISSIONS.APPLY_TO_JOB,
  PERMISSIONS.VIEW_OWN_APPLICATIONS,
];
 
const COMPANY_PERMISSIONS = [
  PERMISSIONS.LOGIN,
  PERMISSIONS.REGISTER,
  PERMISSIONS.VERIFY_EMAIL,
  PERMISSIONS.VIEW_JOBS,
  PERMISSIONS.VIEW_JOB_DETAIL,
  PERMISSIONS.LOGOUT,
  PERMISSIONS.VIEW_OWN_PROFILE,
  PERMISSIONS.EDIT_OWN_PROFILE,
  PERMISSIONS.CREATE_JOB_POSTING,
  PERMISSIONS.EDIT_OWN_JOB_POSTING,
  PERMISSIONS.DELETE_OWN_JOB_POSTING,
  PERMISSIONS.VIEW_OWN_APPLICANTS,
  PERMISSIONS.UPDATE_APPLICATION_STATUS,
];
 
const ADMIN_PERMISSIONS = [
  // Inherits everything from all roles
  ...STUDENT_PERMISSIONS,
  ...COMPANY_PERMISSIONS,
  
  // Admin-only
  PERMISSIONS.APPROVE_COMPANY,
  PERMISSIONS.REJECT_COMPANY,
  PERMISSIONS.APPROVE_JOB_POSTING,
  PERMISSIONS.REJECT_JOB_POSTING,
  PERMISSIONS.EDIT_ANY_JOB_POSTING,
  PERMISSIONS.DELETE_ANY_JOB_POSTING,
  PERMISSIONS.VIEW_ALL_USERS,
  PERMISSIONS.ACTIVATE_USER,
  PERMISSIONS.DEACTIVATE_USER,
  PERMISSIONS.DELETE_USER,
  PERMISSIONS.CHANGE_USER_ROLE,
  PERMISSIONS.VIEW_ALL_APPLICATIONS,
  PERMISSIONS.VIEW_ALL_JOB_POSTINGS,
  PERMISSIONS.SEND_NOTIFICATION,
  PERMISSIONS.VIEW_AUDIT_LOG,
  PERMISSIONS.VIEW_REPORTS, // TO_DO: pending implementation
];
 

const ROLE_MASK = {
  student: STUDENT_PERMISSIONS.reduce((mask, perm) => mask | perm, 0),
  intern: INTERN_PERMISSIONS.reduce((mask, perm) => mask | perm, 0 ),
  graduate: GRADUATE_PERMISSIONS.reduce((mask, perm) => mask | perm, 0),
  company: COMPANY_PERMISSIONS.reduce((mask, perm) => mask | perm, 0),
  admin: ADMIN_PERMISSIONS.reduce((mask, perm) => mask | perm, 0)
};

const hasPermission = (userMask, permissions) => {
  return (userMask & permissions) == permissions;
}

module.export = {

  PERMISSIONS,
  STUDENT_PERMISSIONS,
  INTERN_PERMISSIONS,
  GRADUATE_PERMISSIONS,
  COMPANY_PERMISSIONS,
  ADMIN_PERMISSIONS,
  ROLE_MASK,
  hasPermission
};

